# Generated by Django 5.0.3 on 2024-07-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
